# Generated by Django 3.1.3 on 2021-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201231_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='desc',
            field=models.TextField(max_length=20),
        ),
    ]
